version: "3.9"
services:
  webserver:
    container_name: webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
      - ./apache_php_conf/php.ini:/usr/local/etc/php/php.ini
      - ./apache_log/:/var/log/apache2
    ports:
      - 80:80
      #- 9003:9003
    depends_on:
      - mysql-db
    networks:
      - local
    #extra_hosts:
      #- "host.docker.internal:host-gateway"

  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: test_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data/:/var/lib/mysql
    networks:
      - local

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql-db
    ports:
      - "8001:80"
    environment:
      PMA_HOST: mysql-db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - local

networks:
  local:
    driver: bridge